### ISSUE TITLE
Machine is a ‘data class’

### ISSUE THREAD

**Issue by YujingSong** [Software-Quality-UMM-CSci-4659-F18/smells-in-machine-shop-simulator-songnathan#1]
In MachineShopSimulator the method changeState should be in Machine, takes no arguments
--This also (probably allows us to make a lot of methods used in that method private
--Change lines 39, 138, 128

the method getJobQ ruins the privacy of jobQ. Instead only implement the needed functionality
--boolean hasNoJobs() returns true if the jobQ is empty, false otherwise
--Change setActiveJob to take no arguments and remove the first element of the jobQ as the new activeJob. --This method can also update the totalWait and numTasks fields automatically. It can also tell the new activeJob to removeNextTask()
--Implement putJobOnQ(Job job)
--Idea: Have machines tell the EventList that they’re done when they’re done rather than having all that logic in MachineShopSimulator

**Comment by globbycodes** [comment]
Very clear documentation of the issue. I can clearly see why and what is going to be changed.

**Comment by CMenne** [comment]
I think your documentation provides a good explanation of the problem. I'm unsure of how I feel about detailed plan to address the issue. One concern that I have is if the plan to fix the issue changes after you have been working on implementing it. You would then have to edit this issue to match the changed plan. However, I'm unsure if this is a legitimate concern.
